import Cursor from "@/layout/Cursor";

export const metadata = {
  title: "Kura | Intro",
  description: "Generated by create next app",
};

const Intro = () => {
  return (
    <div
      className="kura_tm_all_wrap w-full h-auto clear-both float-left relative"
      data-magic-cursor="show"
    >
      {" "}
      {/* If you want disable magic cursor change value to "hide" */}
      <div className="kura_tm_intro">
        <div className="kura_tm_intro_fixed_price">
          <span className="anim" />
          <span className="anim" />
          <span className="anim" />
          <a
            href="https://themeforest.net/user/codeefly/portfolio"
            target="_blank"
            className="pricing-info anim"
          >
            Buy
          </a>
        </div>
        <div className="short_info">
          <img src="assets/img/logo/dark.png" alt="" />
          <h3>Tailwind CSS Personal React NextJS Portfolio Template</h3>
        </div>
        <span className="intro_line" />
        <span className="intro_line_2" />
        <span className="intro_line_3" />
        <div className="demos">
          <div className="left">
            <div className="desc">
              <img src="assets/img/intro/1.png" alt="" />
              <h3 className="title">Light Demo</h3>
            </div>
            <a className="intro_link" href="/" target="_blank" />
          </div>
          <div className="right">
            <div className="desc">
              <img src="assets/img/intro/2.png" alt="" />
              <h3 className="title">Dark Demo</h3>
            </div>
            <a className="intro_link" href="/dark" target="_blank" />
          </div>
        </div>
      </div>
      {/* CURSOR */}
      <Cursor />
      {/* /CURSOR */}
    </div>
  );
};
export default Intro;
